[project]
name = "p21-script"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "pandas>=1.3.0",
    "sqlalchemy>=2.0",
    "psycopg2-binary>=2.9.0",
]
